apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete
  namespace: k8s-deploy-lanchonete
  labels:
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lanchonete-app
  template:
    metadata:
      labels:
        app: lanchonete-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
             - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - amd64
      containers:
        - name: deployment-k8s
        #image: minha-imagem:latest
                  env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
       kubernetes.io/os: linux

