apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lanchonete-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:246021362648:secret:lanchonete-secrets"
        jmesPath: 
            - path: db_username
              objectAlias: DB_USER
            - path: db_password
              objectAlias: DB_PASSWORD
