apiVersion: v1
kind: Service
metadata:
  name: service-alb-lanchonete
spec:
  type: LoadBalancer
  selector:
    app: lanchonete-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
