name: Lanchonete App CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-tests:
    name: "Continuous integration"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build --if-present

      - name: Run tests
        run: npm test

  create-docker-image:
    name: "Build Docker image"
    runs-on: ubuntu-latest
    needs: build-and-tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Build docker
        run: echo "build docker" && exit 0

  deploy:
    name: "Continuous Delivery"
    runs-on: ubuntu-latest
    needs: create-docker-image
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy app
        run: echo "deploy" && exit 0